// apps/web/scripts/embed-legal.mjs
//
// docs/templates/legal/*.md を読んで、apps/web/src/pages/legal-content.gen.ts に
// TypeScript モジュールとして埋め込む。Workers / Vitest どちらからも import できる
// 形に。冒頭の DRAFT メタブロック (`> **Status: DRAFT…**` ブロック) は web 公開
// 時に不要なので除去する。
//
// 実行: `node scripts/embed-legal.mjs` (apps/web/ から)
// または `pnpm build:legal` (package.json の script)。

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const legalDir = resolve(here, '../../../docs/templates/legal');
const outPath = resolve(here, '../src/pages/legal-content.gen.ts');

const SLUGS = {
  terms: 'terms-of-service.md',
  privacy: 'privacy-policy.md',
  refunds: 'refund-policy.md',
  'specified-commercial-transactions': 'specified-commercial-transactions.md',
};

function stripDraftBlock(md) {
  // 冒頭の `# Title` の直後にある `> **Status: DRAFT …` ブロックを除去する。
  // ブロックは英語版なら **Effective date:** で、日本語版なら **最終更新:** で
  // 終わる (それらが本文の始まり)。
  return md.replace(/^> \*\*Status[\s\S]*?(?=^\*\*(?:Effective date|最終更新))/m, '');
}

const lines = [
  '// AUTO-GENERATED by apps/web/scripts/embed-legal.mjs — do not edit by hand.',
  '// To regenerate: from apps/web/, run `pnpm build:legal` (or the embed script directly).',
  '',
  'export const LEGAL_CONTENT = {',
];
for (const [slug, file] of Object.entries(SLUGS)) {
  const content = readFileSync(resolve(legalDir, file), 'utf-8');
  const stripped = stripDraftBlock(content);
  // template literal にそのまま入れるため、backtick / ${ / バックスラッシュを
  // エスケープ。
  const escaped = stripped
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  lines.push(`  '${slug}': \`${escaped}\`,`);
}
lines.push('} as const;');
lines.push('');
lines.push("export type LegalContentSlug = keyof typeof LEGAL_CONTENT;");
lines.push('');

writeFileSync(outPath, lines.join('\n'), 'utf-8');
const slugCount = Object.keys(SLUGS).length;
console.log(`embedded ${slugCount} legal docs to ${outPath}`);
