// AUTO-GENERATED by apps/web/scripts/embed-legal.mjs — do not edit by hand.
// To regenerate: from apps/web/, run `pnpm build:legal` (or the embed script directly).

export const LEGAL_CONTENT = {
  'terms': `# Terms of Service

**Effective date: <EFFECTIVE_DATE>**

These Terms of Service ("Terms") govern your use of the migrate-bot service
("Service") provided by <OPERATOR_LEGAL_NAME> ("we", "us", "our"). By
installing the migrate-bot GitHub App, paying for a migration, or otherwise
using the Service, you ("Customer", "you") agree to these Terms.

If you do not agree to these Terms, do not use the Service.

## 1. The Service

The Service automatically converts a Next.js application from the Pages Router
to the App Router and produces a draft pull request in your GitHub repository.
The Service operates as a GitHub App and processes the source code of one
selected repository per paid order.

The Service uses third-party AI providers (currently Anthropic) to perform
the code transformation. By using the Service you acknowledge that the
contents of the source files in your selected repository will be transmitted
to those providers solely for the purpose of producing the migration output.

## 2. Eligibility and Account

You represent that:

- You are at least 18 years old (or the age of majority in your jurisdiction).
- You have the authority to grant migrate-bot access to the GitHub
  organization or user account whose repository you select.
- You are not a competitor of the Service intending to reverse-engineer it.
- You will not use the Service from a country subject to a comprehensive U.S.
  trade embargo.

You are responsible for the security of your GitHub account and the
correctness of your billing information.

## 3. Permitted Use

You may use the Service to migrate repositories you own or repositories your
organization owns and on which you have authority to install third-party
GitHub Apps. You may use the resulting pull request and migrated code without
restriction in your own products.

## 4. Prohibited Use

You may not:

- Submit a repository you do not have authority to modify.
- Submit content that is unlawful, infringing, malicious (malware,
  cryptominers, etc.), or that violates third-party rights.
- Attempt to circumvent rate limits, bypass billing, or extract proprietary
  prompts or system messages from the Service.
- Use the Service to migrate repositories whose content cannot be lawfully
  transmitted to a third-party AI processor (for example, repositories that
  contain regulated personal data subject to data-residency requirements
  incompatible with our subprocessors). See Privacy Policy.
- Resell the Service to third parties without our prior written consent.

We may suspend or terminate access if we reasonably believe these terms have
been violated.

## 5. Pricing and Payment

Pricing is per-migration and is presented at checkout in U.S. dollars. The
current plans are:

| Plan | Eligibility | Price (USD) |
|---|---|---|
| Small | Up to 100 files in \`pages/\` and \`components/\` | $99 |
| Medium | Up to 500 files | $249 |
| Large | Up to 2,000 files | $499 |
| Enterprise | More than 2,000 files or monorepo | Custom quote |

Payments are processed by Stripe. By submitting payment you authorize Stripe
and us to charge your selected payment method for the chosen plan.

We may change pricing at any time. Changes do not apply retroactively to
already-purchased migrations.

## 6. Refunds

Refunds are governed by our [Refund Policy](./refund-policy.md), which is
incorporated into these Terms by reference. In summary: if our automated
verification (typecheck and \`next build\`) cannot reach a passing state within
14 days of payment for reasons attributable to the Service, you are entitled
to a full refund of the order price.

## 7. Intellectual Property

### 7.1 Your code

You retain all rights, title, and interest in and to your repository and any
migrated output. We do not claim any ownership of your code or your migrated
output.

### 7.2 Our Service

The migrate-bot software, prompts, agent infrastructure, and documentation
are owned by us. Nothing in these Terms grants you a license to our software
or prompts beyond using the Service as documented.

### 7.3 No training-data use

We do not retain your repository contents after the migration job completes,
and we do not use your repository contents to train any machine-learning
model. See the Privacy Policy for details on data handling.

## 8. Third-party services

The Service depends on third-party services including:

- **Anthropic** (LLM provider used for code transformation)
- **GitHub** (repository hosting and OAuth provider)
- **Stripe** (payment processing)
- **Cloudflare** (web infrastructure)
- **Fly.io** (compute infrastructure)
- **Resend** (transactional email)

Their respective terms and privacy policies apply to your interactions with
them. We are not responsible for actions or omissions of these third parties,
but we will work in good faith to address service incidents.

## 9. Service availability and disclaimers

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

We do not warrant that the migrated output will be free of bugs, will compile
in every environment, or will be functionally identical to your original
codebase. The output is provided as a *draft* pull request specifically so
that you can review and adjust before merging.

## 10. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL CUMULATIVE LIABILITY UNDER
THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID US FOR THE INDIVIDUAL
MIGRATION ORDER GIVING RISE TO THE CLAIM.

WE WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR
EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION LOST PROFITS, LOST DATA,
LOST GOODWILL, OR BUSINESS INTERRUPTION, EVEN IF WE HAVE BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

Some jurisdictions do not allow the exclusion or limitation of certain
damages; these provisions shall apply to the maximum extent permitted by
applicable law.

## 11. Indemnification

You agree to indemnify and hold us harmless from claims, damages, and
expenses (including reasonable attorneys' fees) arising from:

- Your breach of these Terms;
- Your content or repository (including infringement of third-party rights);
- Your violation of applicable law in connection with the Service.

## 12. Termination

You may stop using the Service at any time. We may terminate or suspend
your access if we reasonably believe you have violated these Terms or if
required by law. Sections 7, 9, 10, 11, and 13 survive termination.

## 13. Governing law and disputes

These Terms are governed by the laws of <GOVERNING_LAW>, without regard to
conflict-of-law principles. Any dispute will be resolved in the courts of
<GOVERNING_LAW>, except that either party may seek equitable relief in any
court of competent jurisdiction to protect its intellectual property.

## 14. Changes to these Terms

We may update these Terms from time to time. The current version is always
posted at https://<DOMAIN>/terms. Material changes will be announced by
email to active customers at least 14 days before they take effect.

## 15. Contact

Questions about these Terms can be sent to <CONTACT_EMAIL>.
`,
  'privacy': `# Privacy Policy

**Effective date: <EFFECTIVE_DATE>**

This Privacy Policy describes how <OPERATOR_LEGAL_NAME> ("we", "us")
collects, uses, and protects information when you use migrate-bot
("Service").

## 1. Information we collect

### 1.1 Information you provide

- **Email address** — collected at checkout to send order confirmation,
  PR-ready notification, and support correspondence.
- **Payment method** — handled directly by Stripe; we never see or store
  your full card number, CVC, or expiration date.
- **GitHub installation context** — your GitHub user/organization handle
  and the installation ID for the repository you select.

### 1.2 Information collected automatically

- **Repository metadata** — file paths, file types, and line counts of the
  selected repository (used to determine plan size and migration scope).
- **Migration logs** — timestamps, state transitions, error messages, token
  counts, and cost. Logs do not include source code snippets; only file
  paths, line numbers, and short error excerpts.
- **Operational logs** — request timestamps, IP addresses, and user agents
  for security monitoring (kept for 30 days then purged).

### 1.3 Repository contents (transient)

While a migration job is running, the source code of the selected repository
is cloned onto a temporary virtual machine on our compute infrastructure
(see "Subprocessors") and the contents of source files are sent to the AI
provider for transformation. **Repository contents are not retained after
the job completes.** The temporary virtual machine is destroyed at job end,
typically within minutes.

We never use your repository contents to train, fine-tune, or improve any
machine-learning model.

## 2. How we use information

We use the information described above to:

- Provide the migration service and produce the draft pull request
- Process your payment and issue refunds when applicable
- Send order-related and account-related email notifications
- Monitor service health and prevent abuse
- Comply with legal obligations

We do not sell your personal information. We do not use it for behavioral
advertising.

## 3. Subprocessors

We use the following third-party processors, each governed by their own
privacy policy:

| Subprocessor | Purpose | Data shared |
|---|---|---|
| Anthropic, PBC | LLM-based code transformation | Source file contents (during job) |
| GitHub, Inc. | Repository hosting, App auth, PR creation | GitHub installation context, branch and PR metadata |
| Stripe, Inc. | Payment processing | Customer email, billing details |
| Cloudflare, Inc. | Web hosting, queue, database | All non-payment service data |
| Fly.io | Job execution VM | Source code (during job only) |
| Resend, Inc. | Transactional email delivery | Customer email and message content |

Anthropic's API terms (as of this policy's effective date) state that data
sent to the Claude API is not used for model training. We rely on this
contractual commitment.

## 4. Data retention

| Data type | Retention |
|---|---|
| Repository contents | Deleted at job end (typically minutes) |
| Migration logs (paths, line numbers, timing, costs) | 1 year |
| Email address and order history | Retained for the life of the customer relationship + 7 years (tax / accounting requirements) |
| Operational logs (IP, user-agent) | 30 days |
| Stripe records | Retained by Stripe per their policy |

## 5. International data transfers

Our infrastructure runs primarily on Cloudflare and Fly.io, which operate
globally. Data may be processed in regions outside your country of
residence, including the United States. We rely on the Standard Contractual
Clauses or equivalent transfer mechanisms offered by our subprocessors.

If you require data residency in a specific region (e.g., EU only), please
contact <CONTACT_EMAIL> before paying. Some plans may not be available
under residency restrictions.

## 6. Security

- Customer repository contents are processed only on isolated, ephemeral
  virtual machines.
- Secrets (API keys, GitHub App private key, Stripe key) are stored in
  Cloudflare Secrets and Fly.io Secrets and rotated at least every six
  months or upon suspected compromise.
- All in-transit traffic uses HTTPS.
- Webhooks are signature-verified.

## 7. Your rights

Depending on your jurisdiction, you may have the right to:

- **Access** — request a copy of personal data we hold about you
- **Correction** — request correction of inaccurate data
- **Deletion** — request deletion of your data (subject to legal-retention
  obligations such as tax records)
- **Portability** — request a machine-readable copy of your data
- **Object / restrict** — object to certain processing activities
- **Withdraw consent** — where processing is based on consent

To exercise any of these rights, contact <CONTACT_EMAIL>. We will respond
within 30 days (or sooner where required by applicable law).

For California residents (CCPA): we do not sell personal information. You
have rights to know, delete, and opt out (no sale to opt out from).

For EU/UK residents (GDPR): we process data under the legal bases of
**contract performance** (to provide the Service you paid for) and
**legitimate interest** (security and abuse prevention).

For Japan residents (個人情報保護法 / APPI): for inquiries please contact
<CONTACT_EMAIL>. Our 個人情報取扱事業者 representative is
<OPERATOR_LEGAL_NAME>, <OPERATOR_ADDRESS>.

## 8. Children's privacy

The Service is not directed to children under the age of 16. We do not
knowingly collect personal information from children. If you believe we
have inadvertently collected such information, please contact us for
deletion.

## 9. Changes to this policy

We may update this policy from time to time. Material changes will be
announced by email to active customers at least 14 days before they take
effect. The current version is always posted at
https://<DOMAIN>/privacy.

## 10. Contact

Privacy inquiries: <CONTACT_EMAIL>
Mail: <OPERATOR_LEGAL_NAME>, <OPERATOR_ADDRESS>
`,
  'refunds': `# Refund Policy

**Effective date: <EFFECTIVE_DATE>**

We are committed to delivering working migration output. This Refund Policy
explains when you are entitled to a refund and how to request one.

## 1. Refund-eligible scenarios

You are eligible for a **full refund** of the order price if **any** of the
following applies and you contact us within 14 days of payment:

- Our automated verification (TypeScript typecheck and \`next build\`) cannot
  reach a passing state for reasons attributable to the Service.
- The migration job fails to complete due to a Service-side defect (for
  example, a runtime error inside our agent that we cannot reproduce as a
  pre-existing condition in your repository).
- Our agent identifies a blocker in your repository that we did not detect
  upfront (for example, a custom server, monorepo layout that our analyzer
  missed, or a regulated dependency we cannot process). In this case the
  refund is automatic; the migration job is aborted and the refund is
  initiated within minutes.

In refund-eligible cases, the refund covers the full order price. Refunds
are issued back to the original payment method via Stripe and typically
clear within 5–10 business days depending on your card issuer.

## 2. Not refund-eligible

The following situations are **not** eligible for refund:

- The CI / typecheck / build failures arise from changes you made to your
  repository after our migration job ran (including custom tests we did
  not have visibility into at job time).
- The CI / typecheck / build failures arise from your custom configuration,
  proprietary plugins, internal libraries, or third-party services we have
  no visibility into.
- You change your mind after the draft pull request was successfully
  produced. Once a PR is open and our verification passed, the order is
  considered fulfilled.
- You requested cancellation but the migration job had already completed
  successfully.

## 3. Partial refunds

We do not issue partial refunds. The unit of sale is the migration job; we
either deliver a working draft PR or we refund the entire order price.

## 4. Cancellation before job completion

If you contact us before the migration job has produced a draft PR (typical
window: 0–10 minutes after payment), we may be able to cancel and refund
the order, but cancellation is not guaranteed once the job has started.
Email <CONTACT_EMAIL> immediately if you wish to cancel.

## 5. How to request a refund

Email <CONTACT_EMAIL> with:

1. The email address used at checkout
2. The repository full name (e.g., \`octocat/hello\`)
3. A short description of the issue

We will respond within 2 business days. If your case falls under Section 1,
we will initiate the refund through Stripe immediately. We may ask
clarifying questions before issuing a refund where the cause is unclear.

## 6. Disputes

If you disagree with our refund decision, please reply to our determination
email and we will review the case again with a different reviewer. If we
still cannot reach an agreement, you retain your statutory rights under
applicable consumer-protection laws.

## 7. Changes

We may update this Refund Policy from time to time. The current version is
always posted at https://<DOMAIN>/refunds.
`,
  'specified-commercial-transactions': `# 特定商取引法に基づく表記

**最終更新: <EFFECTIVE_DATE>**

| 項目 | 内容 |
|---|---|
| **販売事業者の名称** | <OPERATOR_LEGAL_NAME> |
| **代表者の氏名** | <OPERATOR_LEGAL_NAME> |
| **所在地** | <OPERATOR_ADDRESS><br>※請求があった場合に遅滞なく開示します |
| **電話番号** | <CONTACT_PHONE><br>※請求があった場合に遅滞なく開示します |
| **メールアドレス** | <CONTACT_EMAIL> |
| **販売 URL** | https://<DOMAIN> |
| **販売価格** | 各プラン詳細は https://<DOMAIN>/#pricing に表示。米ドル建て決済。日本円換算は決済時の Stripe レートを適用 |
| **商品代金以外の必要料金** | 銀行送金・カード会社が課す為替手数料・利用料はお客様負担となる場合があります |
| **支払方法** | クレジットカード(Visa / Mastercard / American Express / JCB / Discover、Stripe 経由) |
| **支払時期** | 注文時に Stripe Checkout 経由で全額即時決済 |
| **役務の提供時期** | 注文(決済成功)後、ほぼ自動で開始されます。完了までの目安時間は対象リポジトリの規模により 5〜30 分程度です。完了時に登録メールアドレス宛にお知らせします |
| **返品・キャンセルの可否および条件** | 本サービスはカスタマイズされたデジタルサービスであり、原則として役務提供完了後の返品・キャンセルはお受けできません。<br>ただし**当社側の不具合によりサービスを完了できなかった場合**は決済日から 14 日以内のご連絡で全額返金します。詳細は[返金ポリシー](./refund-policy.md)を参照ください |
| **動作環境** | お客様の Next.js リポジトリが Pages Router で記述されていること、 GitHub に存在すること、当社の GitHub App をインストール可能であることが前提です。詳細は[利用規約](./terms-of-service.md) §2、§4 を参照 |
| **不良品・契約不適合への対応** | 当社の不具合によりサービスを完了できなかった場合は[返金ポリシー](./refund-policy.md)に従い全額返金します。提供物そのものに不適合があった場合は <CONTACT_EMAIL> までご連絡ください |

## 補足

- 本サービスは法人・個人事業主向けの開発支援ツールです。一般消費者向けの
  EC サイトではありませんが、特定商取引法第 11 条に基づき本表記を掲載しています。
- 日本以外の地域からの購入も可能です。日本居住者の購入においては本表記が
  優先します。
- 本サービスは弊社のソフトウェアと第三者の AI サービス
  (Anthropic Claude API)を組み合わせて提供されます。詳細は[プライバシー
  ポリシー](./privacy-policy.md) §3 を参照ください。
`,
} as const;

export type LegalContentSlug = keyof typeof LEGAL_CONTENT;
