// AUTO-GENERATED by apps/web/scripts/embed-legal.mjs — do not edit by hand.
// To regenerate: from apps/web/, run `pnpm build:legal` (or the embed script directly).

export const LEGAL_CONTENT = {
  'terms': `# Terms of Service

**Effective date: <EFFECTIVE_DATE>**

These Terms of Service ("Terms") govern your use of the migrate-bot service
("Service") provided by <OPERATOR_LEGAL_NAME> ("we", "us", "our"). By
installing the migrate-bot GitHub App, paying for a migration, or otherwise
using the Service, you ("Customer", "you") agree to these Terms.

If you do not agree to these Terms, do not use the Service.

## 1. The Service

The Service automatically converts a Next.js application from the Pages Router
to the App Router and produces a draft pull request in your GitHub repository.
The Service operates as a GitHub App and processes the source code of one
selected repository per paid order.

The Service uses third-party AI providers (currently Anthropic) to perform
the code transformation. By using the Service you acknowledge that the
contents of the source files in your selected repository will be transmitted
to those providers solely for the purpose of producing the migration output.

## 2. Eligibility and Account

You represent that:

- You are at least 18 years old (or the age of majority in your jurisdiction).
- You have the authority to grant migrate-bot access to the GitHub
  organization or user account whose repository you select.
- You are not a competitor of the Service intending to reverse-engineer it.
- You will not use the Service from a country subject to a comprehensive U.S.
  trade embargo.
- **You are not a resident of, and do not access the Service from, the
  European Economic Area (EEA), the United Kingdom, or Switzerland.** The
  Service is not currently offered to residents of those jurisdictions.
  If you are unsure whether this restriction applies to you, please contact
  us at <CONTACT_EMAIL> before paying.

You are responsible for the security of your GitHub account and the
correctness of your billing information.

## 3. Permitted Use

You may use the Service to migrate repositories you own or repositories your
organization owns and on which you have authority to install third-party
GitHub Apps. You may use the resulting pull request and migrated code without
restriction in your own products.

## 4. Prohibited Use

You may not:

- Submit a repository you do not have authority to modify.
- Submit content that is unlawful, infringing, malicious (malware,
  cryptominers, etc.), or that violates third-party rights.
- Attempt to circumvent rate limits, bypass billing, or extract proprietary
  prompts or system messages from the Service.
- Use the Service to migrate repositories whose content cannot be lawfully
  transmitted to a third-party AI processor (for example, repositories that
  contain regulated personal data subject to data-residency requirements
  incompatible with our subprocessors). See Privacy Policy.
- Resell the Service to third parties without our prior written consent.

We may suspend or terminate access if we reasonably believe these terms have
been violated.

## 5. Pricing and Payment

Pricing is per-migration and is presented at checkout in U.S. dollars. The
current plans are:

| Plan | Eligibility | Price (USD) |
|---|---|---|
| Small | Up to 100 files in \`pages/\` and \`components/\` | $99 |
| Medium | Up to 500 files | $249 |
| Large | Up to 2,000 files | $499 |
| Enterprise | More than 2,000 files or monorepo | Custom quote |

Payments are processed by Stripe. By submitting payment you authorize Stripe
and us to charge your selected payment method for the chosen plan.

We may change pricing at any time. Changes do not apply retroactively to
already-purchased migrations.

## 6. Refunds

Refunds are governed by our [Refund Policy](/legal/refunds), which is
incorporated into these Terms by reference. In summary, you are entitled to
a full refund of the order price for any failure attributable to the
Service — including unrecoverable verification failure within the 14-day
service-delivery window, agent-side defects, and blockers we did not
detect upfront. The full list of refund-eligible scenarios, exclusions,
and the 30-day notification window during which you may raise issues are
described in the Refund Policy.

## 7. Intellectual Property

### 7.1 Your code

You retain all rights, title, and interest in and to your repository and any
migrated output. We do not claim any ownership of your code or your migrated
output.

### 7.2 Our Service

The migrate-bot software, prompts, agent infrastructure, and documentation
are owned by us. Nothing in these Terms grants you a license to our software
or prompts beyond using the Service as documented.

### 7.3 No training-data use

We do not retain your repository contents after the migration job completes,
and we do not use your repository contents to train any machine-learning
model. See the Privacy Policy for details on data handling.

## 8. Third-party services

The Service depends on third-party services including:

- **Anthropic** (LLM provider used for code transformation)
- **GitHub** (repository hosting and OAuth provider)
- **Stripe** (payment processing)
- **Cloudflare** (web infrastructure)
- **Fly.io** (compute infrastructure)
- **Resend** (transactional email)

Their respective terms and privacy policies apply to your interactions with
them. We are not responsible for actions or omissions of these third parties,
but we will work in good faith to address service incidents.

## 9. Service availability and disclaimers

The Service is provided on an "as is" and "as available" basis. Except to
the extent prohibited by applicable consumer-protection law (including, for
Japan-resident customers, the Consumer Contract Act, Articles 8 through
10), we make no express or implied warranty of merchantability, fitness for
a particular purpose, or non-infringement.

We do not warrant that the migrated output will be free of bugs, will
compile in every environment, or will be functionally identical to your
original codebase. The output is provided as a *draft* pull request
specifically so that you can review and adjust before merging.

**Nothing in this section excludes or limits our liability for damages
caused by our intentional misconduct or gross negligence (故意又は重大な
過失). The limitations in this Section 9 and Section 10 apply only to
ordinary negligence (軽過失) and to the maximum extent permitted by
applicable law.**

## 10. Limitation of liability

Subject to Section 9 and to applicable consumer-protection law, our total
cumulative liability under these Terms for any claim arising out of or
relating to a particular migration order shall not exceed the amount you
paid us for that order.

To the maximum extent permitted by applicable law and except in the case
of our intentional misconduct or gross negligence, we will not be liable
for indirect, incidental, consequential, special, or exemplary damages,
including without limitation lost profits, lost data, lost goodwill, or
business interruption, even if we have been advised of the possibility of
such damages.

**For Japan-resident consumer customers**: Pursuant to the Consumer
Contract Act (消費者契約法) Articles 8 and 10, none of the limitations
in this Section 10 shall apply where they would void the limitation
under those Articles. In particular, this Section 10 does not exclude
liability arising from our intentional misconduct or gross negligence,
and does not impose any obligation that would unilaterally harm consumer
interests in violation of Civil Code Article 1, Paragraph 2.

## 11. Indemnification

To the extent permitted by applicable law, and only where you have acted
intentionally or with negligence, you agree to indemnify and hold us
harmless from third-party claims, damages, and reasonable expenses
arising from:

- Your material breach of these Terms;
- Your repository content infringing on third-party rights or violating
  applicable law (where you knew or should have known of the violation);
- Your unauthorized or unlawful use of the Service.

This Section 11 does not apply to claims caused in whole or in part by
our intentional misconduct or gross negligence. For Japan-resident
consumer customers, this Section 11 is to be construed and applied
consistently with the Consumer Contract Act, Article 10, and shall not
operate to unilaterally harm consumer interests beyond what general law
would impose.

## 12. Termination

You may stop using the Service at any time. We may terminate or suspend
your access if we reasonably believe you have violated these Terms or if
required by law. Sections 7, 9, 10, 11, and 13 survive termination.

## 13. Governing law and disputes

These Terms are governed by the laws of Japan, without regard to
conflict-of-law principles. The Tokyo District Court (東京地方裁判所)
shall have non-exclusive jurisdiction as the court of first instance for
any dispute arising out of or in connection with these Terms or the
Service.

**For Japan-resident consumer customers**: Notwithstanding the above,
nothing in this Section 13 limits a consumer's right under the Code of
Civil Procedure (民事訴訟法) Article 3-4 to bring proceedings in the
courts of the place of the consumer's domicile at the time of contract
formation, or to invoke any other consumer-protection forum granted by
Japanese law.

Either party may seek equitable relief in any court of competent
jurisdiction to protect its intellectual property.

## 14. Changes to these Terms

We may update these Terms from time to time. The current version is always
posted at https://migrate-bot.dev/terms. Material changes will be announced by
email to active customers at least 14 days before they take effect.

## 15. Contact

Questions about these Terms can be sent to <CONTACT_EMAIL>.
`,
  'privacy': `# Privacy Policy

**Effective date: <EFFECTIVE_DATE>**

This Privacy Policy describes how <OPERATOR_LEGAL_NAME> ("we", "us")
collects, uses, and protects information when you use migrate-bot
("Service").

## 1. Information we collect

### 1.1 Information you provide

- **Email address** — collected at checkout to send order confirmation,
  PR-ready notification, and support correspondence.
- **Payment method** — handled directly by Stripe; we never see or store
  your full card number, CVC, or expiration date.
- **GitHub installation context** — your GitHub user/organization handle
  and the installation ID for the repository you select.

### 1.2 Information collected automatically

- **Repository metadata** — file paths, file types, and line counts of the
  selected repository (used to determine plan size and migration scope).
- **Migration logs** — timestamps, state transitions, error messages, token
  counts, and cost. Logs do not include source code snippets; only file
  paths, line numbers, and short error excerpts.
- **Operational logs** — request timestamps, IP addresses, and user agents
  for security monitoring (kept for 30 days then purged).

### 1.3 Repository contents (transient)

While a migration job is running, the source code of the selected repository
is cloned onto a temporary virtual machine on our compute infrastructure
(see "Subprocessors") and the contents of source files are sent to the AI
provider for transformation. **Repository contents are not retained after
the job completes.** The temporary virtual machine is destroyed at job end,
typically within minutes.

We never use your repository contents to train, fine-tune, or improve any
machine-learning model.

## 2. How we use information

We use the information described above to:

- Provide the migration service and produce the draft pull request
- Process your payment and issue refunds when applicable
- Send order-related and account-related email notifications
- Monitor service health and prevent abuse
- Comply with legal obligations

We do not sell your personal information. We do not use it for behavioral
advertising.

## 3. Subprocessors

We use the following third-party processors to operate the Service.

**Legal characterization under APPI**: We engage each of the
subprocessors below **as 委託 (entrustment of handling) under Japan's
Act on the Protection of Personal Information (個人情報保護法) Article
27, Paragraph 5, Item 1**. We do not provide your personal information
to these subprocessors as third-party provision (第三者提供) requiring
separate consent under APPI Article 27. Each subprocessor processes
data on our instructions and for our purposes only, and we exercise the
supervision required by APPI Article 25 (consignor's supervision
obligation, 委託先監督義務) — including selecting subprocessors who
publish DPAs and security certifications, and reviewing those terms
before engagement.

**Cross-border disclosure under APPI Article 28 / Rule 17**: Because
these subprocessors are located outside Japan, the entrustment is also a
cross-border transfer governed by APPI Article 28. The table below
discloses, for each subprocessor: (i) the subprocessor's location, (ii)
the personal-information protection regime of that location, and (iii)
the protective measures the subprocessor has committed to, in accordance
with APPI Rule 17, Paragraph 2.

By using the Service you provide consent to (a) our entrustment of your
personal information to the subprocessors below for the purposes
described, and (b) the cross-border transfer of that information to the
locations identified.

| Subprocessor | Location | Purpose / data shared | Protection regime in that country | Subprocessor's protective measures |
|---|---|---|---|---|
| **Anthropic, PBC** | United States (operations); Republic of Ireland (DPA governing law for the EU SCC module) | LLM-based code transformation. Source file contents are sent during a job and are not retained on the API after the request completes. | The United States does not have a comprehensive federal personal-information protection statute equivalent to Japan's APPI; protection is provided through sectoral and state laws (e.g., the California Consumer Privacy Act). U.S. government agencies retain certain investigative powers over data held in the U.S. | Anthropic's Data Processing Addendum incorporates the EU Standard Contractual Clauses (Module 2 / Module 3) by reference. Anthropic's API terms contractually prohibit using API inputs to train models. Anthropic deletes API request payloads after processing except as required to operate the service or by law. |
| **GitHub, Inc.** | United States | Repository hosting, App authentication, draft PR creation. Receives the GitHub installation context, branch and PR metadata, and the migration commits (which are derived from your repository content). | Same as above — sectoral / state regime in the U.S. | GitHub publishes a Data Protection Addendum incorporating EU SCCs and is ISO 27001 / SOC 2 certified. |
| **Stripe, Inc.** | United States | Payment processing. Stripe receives customer email, billing details, and card data. We never see or store card numbers, CVC, or expiration. | Same as above. | Stripe is PCI DSS Level 1 certified and incorporates EU SCCs in its DPA. |
| **Cloudflare, Inc.** | United States (HQ); global edge / Workers may execute in any region | Web hosting, queue, primary database (D1). Receives all non-payment service data and operational logs. | Same as above. | Cloudflare publishes a DPA incorporating EU SCCs and is ISO 27001 / SOC 2 / PCI DSS certified. D1 data is stored in a region we select (currently APAC for prod). |
| **Fly.io** | United States | Job execution VM. The temporary VM clones your repository, runs the agent, and is destroyed at job end (typically minutes). | Same as above. | Fly.io publishes a DPA. VMs are isolated per job; secrets injected at boot and not persisted to image. |
| **Resend, Inc.** | United States | Transactional email delivery. Receives the recipient email address and the message content (order confirmation, PR-ready notification, refund notification). | Same as above. | Resend publishes a DPA and incorporates EU SCCs. |

If you do not consent to the entrustment and cross-border transfer
described in this Section 3, please do not use the Service. To withdraw
consent and request deletion after the fact, see Section 7.

## 4. Data retention

| Data type | Retention |
|---|---|
| Repository contents | Deleted at job end (typically minutes) |
| Migration logs (paths, line numbers, timing, costs) | 1 year |
| Email address and order history | Retained for the life of the customer relationship + 7 years (tax / accounting requirements) |
| Operational logs (IP, user-agent) | 30 days |
| Stripe records | Retained by Stripe per their policy |

## 5. International data transfers

The Service is operated from Japan, but processing occurs in the United
States and at globally distributed edge locations operated by our
subprocessors (see Section 3 for the country-by-country breakdown).

For Japan-resident users, by using the Service you provide consent under
APPI Article 28 to the cross-border transfer of your personal information
to the subprocessors and locations identified in Section 3. The
country-of-location, the protection regime of that country, and the
specific protective measures of each subprocessor are disclosed in
Section 3 in accordance with APPI Rule 17.

**The Service is not currently offered to residents of the European
Economic Area, the United Kingdom, or Switzerland** (see Terms of Service
Section 2). Accordingly, we do not undertake processing operations that
would bring this Service within the territorial scope of the GDPR or the
UK / Swiss equivalents. If you believe you have used the Service from one
of those jurisdictions in error, please contact <CONTACT_EMAIL> and we
will delete your data and refund any payment.

If you are a resident of a jurisdiction whose law restricts cross-border
transfer of personal data and you require data residency in a specific
region, please contact <CONTACT_EMAIL> before paying. We may not be able
to support every residency requirement.

## 6. Security

- Customer repository contents are processed only on isolated, ephemeral
  virtual machines.
- Secrets (API keys, GitHub App private key, Stripe key) are stored in
  Cloudflare Secrets and Fly.io Secrets and rotated at least every six
  months or upon suspected compromise.
- All in-transit traffic uses HTTPS.
- Webhooks are signature-verified.

## 7. Your rights

Depending on your jurisdiction, you may have the right to:

- **Access** — request a copy of personal data we hold about you
- **Correction** — request correction of inaccurate data
- **Deletion** — request deletion of your data (subject to legal-retention
  obligations such as tax records)
- **Portability** — request a machine-readable copy of your data
- **Object / restrict** — object to certain processing activities
- **Withdraw consent** — where processing is based on consent

To exercise any of these rights, contact <CONTACT_EMAIL>. We will respond
within 30 days (or sooner where required by applicable law).

**For California residents (CCPA / CPRA)**: we do not sell or share your
personal information for cross-context behavioral advertising. You have
the right to know, delete, correct, and limit use of sensitive personal
information.

**For EU / UK / Switzerland residents**: as stated above and in the
Terms of Service Section 2, the Service is not offered to residents of
these jurisdictions at this time.

**For Japan residents (個人情報保護法 / APPI)**: the personal-information
handling business operator (個人情報取扱事業者) is <OPERATOR_LEGAL_NAME>,
<OPERATOR_ADDRESS>. You may request, with respect to your personal
information that we hold (保有個人データ), (i) disclosure of the
purpose-of-use, (ii) disclosure of the data itself, (iii) correction
of inaccurate data, (iv) suspension of use or erasure where the
data was acquired or used in violation of law, and (v) suspension
of provision to third parties under APPI Articles 32–35. To make
such a request, please email <CONTACT_EMAIL>. We will respond
without delay (and in any case within 30 days) after verifying your
identity. We may charge a reasonable fee for disclosure as permitted
by APPI Rule.

The complaint-handling contact for personal-information matters is
<CONTACT_EMAIL>. The competent supervisory authority is the
Personal Information Protection Commission (個人情報保護委員会,
<https://www.ppc.go.jp/>).

## 8. Children's privacy

The Service is not directed to children under the age of 16. We do not
knowingly collect personal information from children. If you believe we
have inadvertently collected such information, please contact us for
deletion.

## 9. Changes to this policy

We may update this policy from time to time. Material changes will be
announced by email to active customers at least 14 days before they take
effect. The current version is always posted at
https://migrate-bot.dev/privacy.

## 10. Contact

Privacy inquiries: <CONTACT_EMAIL>
Mail: <OPERATOR_LEGAL_NAME>, <OPERATOR_ADDRESS>
`,
  'refunds': `# Refund Policy

**Effective date: <EFFECTIVE_DATE>**

We are committed to delivering working migration output. This Refund Policy
explains when you are entitled to a refund and how to request one.

## 1. Refund-eligible scenarios

You are eligible for a **full refund** of the order price if **any** of the
following applies. You may notify us at any time within **30 days of
payment**; for failures attributable to the Service, we will also process
the refund proactively (without you having to ask) where we can detect
the failure on our side.

- Our automated verification (TypeScript typecheck and \`next build\`) cannot
  reach a passing state within 14 days of payment for reasons attributable
  to the Service.
- The migration job fails to complete due to a Service-side defect (for
  example, a runtime error inside our agent that we cannot reproduce as a
  pre-existing condition in your repository).
- Our agent identifies a blocker in your repository that we did not detect
  upfront (for example, a custom server, monorepo layout that our analyzer
  missed, or a regulated dependency we cannot process). In this case the
  migration job is aborted and the refund is processed promptly upon our
  detection of the blocker.

In refund-eligible cases, the refund covers the full order price. Refunds
are issued back to the original payment method via Stripe and typically
clear within 5–10 business days depending on your card issuer.

> **Note on 14 days vs 30 days**: 14 days is our internal commitment for
> when the Service must complete the migration (役務提供時期). If we
> haven't delivered a passing draft PR by then, the order qualifies for a
> refund. 30 days is the window during which **you** can notify us of
> issues you've observed (e.g., quality problems noticed after merge);
> see Section 5 for the request procedure.

## 2. Not refund-eligible

Subject to Section 2A below, the following situations are **not**
eligible for refund:

- The CI / typecheck / build failures arise from changes you made to your
  repository after our migration job ran (including custom tests we did
  not have visibility into at job time).
- The CI / typecheck / build failures arise from your custom configuration,
  proprietary plugins, internal libraries, or third-party services we have
  no visibility into.
- You change your mind after the draft pull request was successfully
  produced. Once a PR is open and our verification passed, the order is
  considered fulfilled.
- You requested cancellation but the migration job had already completed
  successfully.

## 2A. Carve-out for our intentional misconduct, gross negligence, or non-conformance

Notwithstanding Section 2 and Section 3, the limitations in this Refund
Policy do **not** apply to and do **not** waive any of the following:

- Damage caused by **our intentional misconduct or gross negligence
  (故意又は重大な過失)**;
- A **non-conformance with the contract (契約不適合)** in the migration
  output that exists at the time of delivery and that is attributable to
  the Service. In such a case, you retain your rights under Civil Code
  Articles 562 through 564 (代金減額請求権・履行追完請求権・解除権)
  and equivalent statutory remedies, regardless of the outcome of our
  automated verification step;
- For Japan-resident consumer customers, any right under the Consumer
  Contract Act (消費者契約法), including without limitation Articles
  8, 8-2, 9, and 10. This Refund Policy is to be construed and applied
  consistently with those provisions and shall not operate to
  invalidate the consumer's statutory rights.

If you believe Section 2A applies to your situation, contact
<CONTACT_EMAIL> with the order details and a description of the
non-conformance. We will respond within 2 business days and, where
your claim is well-founded, issue a full or partial refund (or other
remedy) consistent with applicable law.

## 3. Partial refunds

As a general matter we do not issue partial refunds; the unit of sale is
the migration job and we either deliver a working draft PR or refund the
entire order price. **However, this Section 3 does not limit any right
to partial-price reduction (代金減額請求権) under Civil Code Articles
562–564 in cases of contract non-conformance, nor any other partial
remedy required by applicable consumer-protection law.**

## 4. Cancellation before job completion

If you contact us before the migration job has produced a draft PR (typical
window: 0–10 minutes after payment), we may be able to cancel and refund
the order, but cancellation is not guaranteed once the job has started.
Email <CONTACT_EMAIL> immediately if you wish to cancel.

## 5. How to request a refund

Email <CONTACT_EMAIL> with:

1. The email address used at checkout
2. The repository full name (e.g., \`octocat/hello\`)
3. A short description of the issue

We will respond within 2 business days. If your case falls under Section 1,
we will initiate the refund through Stripe immediately. We may ask
clarifying questions before issuing a refund where the cause is unclear.

## 6. Disputes

If you disagree with our refund decision, please reply to our determination
email and we will review the case again with a different reviewer. If we
still cannot reach an agreement, you retain your statutory rights under
applicable consumer-protection laws.

## 7. Changes

We may update this Refund Policy from time to time. The current version is
always posted at https://migrate-bot.dev/refunds.
`,
  'specified-commercial-transactions': `# 特定商取引法に基づく表記

**最終更新: <EFFECTIVE_DATE>**

| 項目 | 内容 |
|---|---|
| **販売事業者の名称** | <OPERATOR_LEGAL_NAME> |
| **代表者の氏名** | <OPERATOR_LEGAL_NAME> |
| **業務責任者** | <OPERATOR_LEGAL_NAME>(事業主本人) |
| **所在地** | <OPERATOR_ADDRESS> |
| **電話番号** | お客様からのご請求があった場合、<CONTACT_EMAIL> 宛のメール受領から **7 日以内** に書面又は電子メールにて遅滞なく開示します。通常時の非開示は、個人事業主のプライバシー保護を目的とした運用です |
| **メールアドレス** | <CONTACT_EMAIL> |
| **販売 URL** | https://migrate-bot.dev |
| **販売価格** | 各プランの価格(米ドル建て)および日本円での参考換算額: <br>・Small: $99(参考: 約 ¥14,800、為替レートにより変動)<br>・Medium: $249(参考: 約 ¥37,400、為替レートにより変動)<br>・Large: $499(参考: 約 ¥74,800、為替レートにより変動)<br>・Enterprise: 個別見積り<br>決済はすべて米ドル建てで行われ、最終的な日本円請求額は決済日の為替レート(Stripe が適用するレート)に基づき各カード会社が確定し、ご請求時にカード明細上で表示されます。上記の参考換算額は本表記の最終更新日時点でのおおよその目安です |
| **商品代金以外の必要料金** | 通信回線使用料、為替手数料、海外取引手数料等、お客様のクレジットカード会社又は決済機関が課す料金はお客様のご負担となります。当社からは追加の手数料は一切請求いたしません |
| **支払方法** | クレジットカード(Visa / Mastercard / American Express / JCB / Discover、Stripe 経由)。当社はカード番号、有効期限、CVC を保持しません |
| **支払時期** | 注文時に Stripe Checkout 経由で全額を即時決済 |
| **申込みの有効期限** | 定めなし(常時お申込みを受け付けています) |
| **役務の提供時期** | 注文(決済成功)後、自動的にジョブが開始されます。**所要時間の上限は決済日から 14 日以内**とし、対象リポジトリの規模・複雑度により概ね 5 分〜数時間程度で完了します。**14 日を超過しても役務提供が完了しない場合は、お客様からのご請求がなくとも当社の判断により[返金ポリシー](/legal/refunds)に基づき全額返金します**。完了時又は返金時に登録メールアドレス宛に通知します |
| **返品・キャンセルの可否および条件** | 本サービスはお客様のリポジトリ毎にカスタマイズされたデジタルサービスのため、原則として役務提供完了後の返品・キャンセルはお受けできません。<br>**ただし当社側に起因する不具合・障害によりサービスを完了できなかった場合**は、決済日から 14 日以内のご連絡で全額返金します。詳細は[返金ポリシー](/legal/refunds)を参照ください |
| **動作環境** | お客様の Next.js リポジトリが (a) GitHub.com 上に存在すること、(b) 当社 GitHub App をインストール可能なリポジトリであること、(c) Next.js Pages Router(\`pages/\` ディレクトリ構成)で記述されていること、を前提とします。Next.js のバージョンは概ね 13.x〜15.x の範囲を対象としますが、特殊な構成(custom server、複雑な monorepo、規制対象の依存関係を含むリポジトリ等)では当社が解析時に対応不可と判定する場合があります。詳細は[利用規約](/legal/terms) §1、§2、§4 を参照 |
| **不良品・契約不適合への対応** | 当社の不具合によりサービスを完了できなかった場合は[返金ポリシー](/legal/refunds)に従い全額返金します。提供物そのもの(draft pull request の内容)に不適合があった場合は <CONTACT_EMAIL> までご連絡ください。当社は故意又は重大な過失による場合を除き、付随的・結果的損害(逸失利益、データ滅失等)について責任を負いません(詳細は[利用規約](/legal/terms) §10) |
| **苦情・お問合せ先** | <CONTACT_EMAIL>(原則 2 営業日以内に返信) |

## 補足

- 本サービスは法人・個人事業主向けの開発支援ツールです。一般消費者向けの
  EC サイトではありませんが、特定商取引法第 11 条に基づき本表記を掲載しています。
- 日本以外の地域からの購入も可能です。日本居住者の購入においては本表記が
  優先します。
- 本サービスは弊社のソフトウェアと第三者の AI サービス
  (Anthropic Claude API)を組み合わせて提供されます。詳細は[プライバシー
  ポリシー](/legal/privacy) §3 を参照ください。
`,
} as const;

export type LegalContentSlug = keyof typeof LEGAL_CONTENT;
